FROM python:3.10-slim

RUN apt-get update && apt-get install -y wget

WORKDIR /app

COPY ingest_data.py .

RUN pip install pandas sqlalchemy psycopg2-binary pyarrow

ENTRYPOINT [ "python", "ingest_data.py" ]